name: github pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '9.15.2'

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'
          cache: 'pnpm'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      - name: Cache Next.js build
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: nextjs-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.json') }}
          restore-keys: |
            nextjs-${{ runner.os }}-

      - name: Create .env.production
        run: env | grep -e NOTION_TOKEN -e NEXT_PUBLIC_GA_ID >> .env.production
        env:
          NOTION_TOKEN: ${{secrets.NOTION_TOKEN}}
          NEXT_PUBLIC_GA_ID: ${{secrets.NEXT_PUBLIC_GA_ID}}

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Create .nojekyll file
        run: touch out/.nojekyll

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        id: deployment
        with:
          path: out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy GitHub Pages
        uses: actions/deploy-pages@v4
