name: github pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '9.15.2'

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'
          cache: 'pnpm'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      - name: Cache Next.js build
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: nextjs-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.json') }}
          restore-keys: |
            nextjs-${{ runner.os }}-

      - name: Create .env.production
        run: env | grep -e NOTION_TOKEN -e NEXT_PUBLIC_GA_ID >> .env.production
        env:
          NOTION_TOKEN: ${{secrets.NOTION_TOKEN}}
          NEXT_PUBLIC_GA_ID: ${{secrets.NEXT_PUBLIC_GA_ID}}

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Create .nojekyll file
        run: touch out/.nojekyll

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Deploy GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_path: ./out
